/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Choices的小木屋",
  "description": "Choices blog",
  "base": "/",
  "headTags": [
    null
  ],
  "pages": [
    {
      "title": "CSS a",
      "frontmatter": {
        "title": "CSS a"
      },
      "regularPath": "/css/",
      "relativePath": "css/README.md",
      "key": "v-67ea6b91",
      "path": "/css/",
      "headers": [
        {
          "level": 2,
          "title": "你好 CSS",
          "slug": "你好-css"
        }
      ]
    },
    {
      "title": "关于我1",
      "frontmatter": {
        "navbar": false,
        "title": "关于我1"
      },
      "regularPath": "/about1.html",
      "relativePath": "about1.md",
      "key": "v-b3a7af9a",
      "path": "/about1.html",
      "headers": [
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ]
    },
    {
      "title": "Hello VuePress",
      "frontmatter": {
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-42d3160c",
      "path": "/"
    },
    {
      "title": "css a",
      "frontmatter": {
        "title": "css a"
      },
      "regularPath": "/css/c-aaa.html",
      "relativePath": "css/c-aaa.md",
      "key": "v-75c2023c",
      "path": "/css/c-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    },
    {
      "title": "css c",
      "frontmatter": {
        "title": "css c"
      },
      "regularPath": "/css/c-ccc.html",
      "relativePath": "css/c-ccc.md",
      "key": "v-f43c48bc",
      "path": "/css/c-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    },
    {
      "title": "css b",
      "frontmatter": {
        "title": "css b"
      },
      "regularPath": "/css/c-bbb.html",
      "relativePath": "css/c-bbb.md",
      "key": "v-25806d42",
      "path": "/css/c-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {
        "navbar": false
      },
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-72e30def",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 2,
          "title": "一级标题",
          "slug": "一级标题"
        },
        {
          "level": 3,
          "title": "二级标题",
          "slug": "二级标题"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-2"
        },
        {
          "level": 2,
          "title": "一级标题1",
          "slug": "一级标题1-3"
        }
      ]
    },
    {
      "title": "JS a",
      "frontmatter": {
        "title": "JS a"
      },
      "regularPath": "/javascript/j-aaa.html",
      "relativePath": "javascript/j-aaa.md",
      "key": "v-60e439a0",
      "path": "/javascript/j-aaa.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    },
    {
      "title": "JS c",
      "frontmatter": {
        "title": "JS c"
      },
      "regularPath": "/javascript/j-ccc.html",
      "relativePath": "javascript/j-ccc.md",
      "key": "v-647d3b2c",
      "path": "/javascript/j-ccc.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    },
    {
      "title": "JS b",
      "frontmatter": {
        "title": "JS b"
      },
      "regularPath": "/javascript/j-bbb.html",
      "relativePath": "javascript/j-bbb.md",
      "key": "v-cbf4e1a4",
      "path": "/javascript/j-bbb.html",
      "headers": [
        {
          "level": 2,
          "title": "二级标题1",
          "slug": "二级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1"
        },
        {
          "level": 3,
          "title": "1 三级标题2",
          "slug": "_1-三级标题2"
        },
        {
          "level": 2,
          "title": "二级标题2",
          "slug": "二级标题2"
        },
        {
          "level": 3,
          "title": "1 三级标题1",
          "slug": "_1-三级标题1-2"
        }
      ]
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/hero.png",
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/about"
      },
      {
        "text": "Languages",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Home",
                "link": "/"
              },
              {
                "text": "Guide",
                "link": "/about"
              }
            ]
          }
        ]
      },
      {
        "text": "External",
        "link": "https://google.com"
      }
    ],
    "sidebar": {
      "/css/": [
        "c-aaa",
        "c-bbb",
        "c-ccc"
      ],
      "/javascript/": [
        "j-aaa",
        "j-bbb",
        "j-ccc"
      ]
    }
  }
}